os: linux
dist: bionic

language: python
python:
  - 3.6

stages:
  - lint
  - test
  - deploy

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_3a3336ff2445_key -iv $encrypted_3a3336ff2445_iv -in .travis/travis-ci_service_account.json.enc -out travis-ci_service_account.json -d

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - make lint

    - stage: test
      install:
        - sudo apt-get -y install libsnappy-dev

        - pip install poetry
        - poetry config virtualenvs.create false
        - poetry install
        - poetry run download_spacy_model
      script:
        - make test

    - stage: deploy
      install:
        - mkdir -p /opt/spark
        - wget -q -O /opt/spark.tgz http://www.gtlib.gatech.edu/pub/apache/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
        - tar xzf /opt/spark.tgz -C /opt
        - mv /opt/spark-2.4.5-bin-hadoop2.7/* /opt/spark
        - rm /opt/spark.tgz
        - export SPARK_HOME=/opt/spark
        - export PATH=$PATH:/opt/spark/bin

        - (cd ${SPARK_HOME} && ./bin/docker-image-tool.sh -t spark -p ./kubernetes/dockerfiles/spark/bindings/python/Dockerfile build)
        - make docker_image
      script:
        - cat travis-ci_service_account.json | docker login -u _json_key https://gcr.io --password-stdin
        - make docker_publish
