apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: streaming
data:
  hosts: a2Fma2EtMC5rYWZrYS5rYWZrYS5zdmMuY2x1c3Rlci5sb2NhbDo5MDkyLGthZmthLTEua2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5MixrYWZrYS0yLmthZmthLmthZmthLnN2Yy5jbHVzdGVyLmxvY2FsOjkwOTI=
